using System.Collections.Generic;
using DeepDive.Network;
using NUnit.Framework;
using Unity.Netcode;
using Unity.Netcode.Components;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace DeepDive.World.Tests
{
    // Guards the part of DiveTestArea that P2-B owns. The dive scene is shared ground and
    // Unity YAML merges badly (docs/plan/WORKFLOW.md: "Ayni ana sahne/prefab uzerinde ayni
    // anda calisilmaz"), so the cheapest protection against a merge quietly dropping the fish,
    // its species or the fog is a test that opens the scene and looks.
    //
    // Everything asserted here is produced by DiveTestAreaSetup.Apply; if this fails, running
    // that menu item again is the repair, not hand-editing the scene.
    public class DiveTestAreaSceneTests
    {
        private const string ScenePath = "Assets/DeepDive/World/Scenes/DiveTestArea.unity";

        private Scene scene;
        private Scene previousActive;
        private bool opened;

        [SetUp]
        public void OpenDiveScene()
        {
            previousActive = SceneManager.GetActiveScene();
            var already = SceneManager.GetSceneByPath(ScenePath);
            opened = !already.IsValid() || !already.isLoaded;
            scene = opened ? EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Additive) : already;
            // RenderSettings always report the active scene, so the fog assertions only see
            // the dive scene while it is the active one.
            SceneManager.SetActiveScene(scene);
        }

        [TearDown]
        public void CloseDiveScene()
        {
            if (previousActive.IsValid() && previousActive.isLoaded) SceneManager.SetActiveScene(previousActive);
            if (opened && scene.IsValid()) EditorSceneManager.CloseScene(scene, true);
        }

        private static List<T> FindAll<T>(Scene scene) where T : Component
        {
            var found = new List<T>();
            foreach (var root in scene.GetRootGameObjects())
                found.AddRange(root.GetComponentsInChildren<T>(true));
            return found;
        }

        private static FishActor SingleFish(Scene scene)
        {
            var fish = FindAll<FishActor>(scene);
            Assert.AreEqual(1, fish.Count, "DiveTestArea must hold exactly one FishActor");
            return fish[0];
        }

        [Test]
        public void SceneHasOneFishWithAValidSpecies()
        {
            var fish = SingleFish(scene);
            Assert.IsNotNull(fish.Species, "FishActor.species is not assigned");
            Assert.IsTrue(fish.Species.IsValid(out var error), error);
            Assert.AreEqual("sea_bass", fish.Species.SpeciesId);
        }

        // The whole reason the scene is authored by a script: an in-scene placed NetworkObject
        // is matched between host and client by this hash, and it is only correct when Unity
        // generated it. A zero here means the object would never resolve on a client.
        [Test]
        public void FishNetworkObjectCarriesAGeneratedHash()
        {
            var fish = SingleFish(scene);
            Assert.IsTrue(fish.TryGetComponent<NetworkObject>(out var networkObject), "NetworkObject is missing");
            Assert.AreNotEqual(0u, networkObject.PrefabIdHash, "GlobalObjectIdHash was never generated by Unity");
        }

        // The host owns fish movement (FishActor.FixedUpdate is server only), so the transform
        // has to be pushed by the server; owner authority would leave clients desynchronised.
        [Test]
        public void FishTransformIsServerAuthoritative()
        {
            var fish = SingleFish(scene);
            Assert.IsTrue(fish.TryGetComponent<NetworkTransform>(out var sync), "NetworkTransform is missing");
            Assert.AreEqual(NetworkTransform.AuthorityModes.Server, sync.AuthorityMode);
            Assert.IsTrue(sync.Interpolate, "clients need interpolation to see smooth swimming");
        }

        // NetworkPlayer raycasts both the harpoon and the pickup with
        // QueryTriggerInteraction.Ignore, so a trigger-only fish could never be hit or taken.
        [Test]
        public void FishIsHittableBySolidCollider()
        {
            var fish = SingleFish(scene);
            var solid = fish.GetComponentsInChildren<Collider>(true).Length > 0;
            Assert.IsTrue(solid, "the fish has no collider at all");
            var hittable = false;
            foreach (var collider in fish.GetComponentsInChildren<Collider>(true))
                if (!collider.isTrigger) hittable = true;
            Assert.IsTrue(hittable, "every fish collider is a trigger, so the harpoon ray passes through");
        }

        [Test]
        public void FishCarriesItsCatchObject()
        {
            var fish = SingleFish(scene);
            Assert.IsTrue(fish.TryGetComponent<CatchObject>(out _),
                "the dead fish becomes the catch in place, so CatchObject shares the NetworkObject");
        }

        // FishMotion holds position instead of leaving the water, so a fish whose wander box
        // pokes outside SwimVolume would spend the dive pinned against a wall.
        [Test]
        public void FishWandersInsideTheWater()
        {
            var fish = SingleFish(scene);
            var water = FindAll<SwimVolume>(scene);
            Assert.AreEqual(1, water.Count, "DiveTestArea must hold exactly one SwimVolume");
            Assert.IsTrue(water[0].TryGetComponent<BoxCollider>(out var volume), "SwimVolume has no BoxCollider");

            var radius = fish.Species.Swim.WanderRadius;
            // FishMotion.VerticalWanderFactor flattens the vertical spread to half.
            var reach = new Vector3(radius, radius * 0.5f, radius);
            var home = fish.transform.position;
            for (var corner = 0; corner < 8; corner++)
            {
                var point = home + new Vector3(
                    (corner & 1) == 0 ? -reach.x : reach.x,
                    (corner & 2) == 0 ? -reach.y : reach.y,
                    (corner & 4) == 0 ? -reach.z : reach.z);
                var local = volume.transform.InverseTransformPoint(point) - volume.center;
                var half = volume.size * 0.5f;
                Assert.IsTrue(
                    Mathf.Abs(local.x) <= half.x && Mathf.Abs(local.y) <= half.y && Mathf.Abs(local.z) <= half.z,
                    $"wander corner {point} falls outside SwimVolume");
            }
        }

        // docs/plan/PHASES.md P2-B closing condition: "basit sualti sisi/isigi test oncesinde
        // mevcut; geri bildirimsiz bos sahne uzerinden tasarim karari verilmiyor".
        [Test]
        public void UnderwaterAtmosphereIsOn()
        {
            Assert.IsTrue(RenderSettings.fog, "underwater fog is off");
            Assert.AreEqual(FogMode.ExponentialSquared, RenderSettings.fogMode);
            Assert.Greater(RenderSettings.fogDensity, 0f);
            Assert.IsNotNull(RenderSettings.sun, "no sun light is bound for the dive");
        }
    }
}
