using System.Collections.Generic;
using DeepDive.Network;
using NUnit.Framework;
using Unity.Netcode;
using Unity.Netcode.Components;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace DeepDive.World.Tests
{
    // Guards the part of DiveTestArea that P2-B owns. The dive scene is shared ground and
    // Unity YAML merges badly (docs/plan/WORKFLOW.md: "Ayni ana sahne/prefab uzerinde ayni
    // anda calisilmaz"), so the cheapest protection against a merge quietly dropping the fish,
    // its species or the fog is a test that opens the scene and looks.
    //
    // Everything asserted here is produced by DiveTestAreaSetup.Apply; if this fails, running
    // that menu item again is the repair, not hand-editing the scene.
    public class DiveTestAreaSceneTests
    {
        private const string ScenePath = "Assets/DeepDive/World/Scenes/DiveTestArea.unity";
        private const string DiverPrefabPath = "Assets/DeepDive/Network/Prefabs/NetworkDiver.prefab";

        private Scene scene;
        private Scene previousActive;
        private bool opened;

        [SetUp]
        public void OpenDiveScene()
        {
            previousActive = SceneManager.GetActiveScene();
            var already = SceneManager.GetSceneByPath(ScenePath);
            opened = !already.IsValid() || !already.isLoaded;
            scene = opened ? EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Additive) : already;
            // RenderSettings always report the active scene, so the fog assertions only see
            // the dive scene while it is the active one.
            SceneManager.SetActiveScene(scene);
        }

        [TearDown]
        public void CloseDiveScene()
        {
            if (previousActive.IsValid() && previousActive.isLoaded) SceneManager.SetActiveScene(previousActive);
            if (opened && scene.IsValid()) EditorSceneManager.CloseScene(scene, true);
        }

        private static List<T> FindAll<T>(Scene scene) where T : Component
        {
            var found = new List<T>();
            foreach (var root in scene.GetRootGameObjects())
                found.AddRange(root.GetComponentsInChildren<T>(true));
            return found;
        }

        private static FishActor SingleFish(Scene scene)
        {
            var fish = FindAll<FishActor>(scene);
            Assert.AreEqual(1, fish.Count, "DiveTestArea must hold exactly one FishActor");
            return fish[0];
        }

        private static NetworkPlayer LoadDiverPrefab(out Camera viewCamera)
        {
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(DiverPrefabPath);
            Assert.IsNotNull(prefab, $"network diver prefab is missing at {DiverPrefabPath}");
            var diver = prefab.GetComponent<NetworkPlayer>();
            Assert.IsNotNull(diver, "NetworkDiver prefab has no NetworkPlayer");
            viewCamera = prefab.GetComponentInChildren<Camera>(true);
            Assert.IsNotNull(viewCamera, "NetworkDiver prefab has no view camera");
            return diver;
        }

        private static float SerializedFloat(Object target, string propertyName)
        {
            var serialized = new SerializedObject(target);
            var property = serialized.FindProperty(propertyName);
            Assert.IsNotNull(property, $"serialized property '{propertyName}' is missing on {target.name}");
            return property.floatValue;
        }

        [Test]
        public void SceneHasOneFishWithAValidSpecies()
        {
            var fish = SingleFish(scene);
            Assert.IsNotNull(fish.Species, "FishActor.species is not assigned");
            Assert.IsTrue(fish.Species.IsValid(out var error), error);
            Assert.AreEqual("sea_bass", fish.Species.SpeciesId);
        }

        // The whole reason the scene is authored by a script: an in-scene placed NetworkObject
        // is matched between host and client by this hash, and it is only correct when Unity
        // generated it. A zero here means the object would never resolve on a client.
        [Test]
        public void FishNetworkObjectCarriesAGeneratedHash()
        {
            var fish = SingleFish(scene);
            Assert.IsTrue(fish.TryGetComponent<NetworkObject>(out var networkObject), "NetworkObject is missing");
            Assert.AreNotEqual(0u, networkObject.PrefabIdHash, "GlobalObjectIdHash was never generated by Unity");
        }

        // The host owns fish movement (FishActor.FixedUpdate is server only), so the transform
        // has to be pushed by the server; owner authority would leave clients desynchronised.
        // Position and every rotation axis are part of gameplay here because the fish can rise,
        // dive and pitch while fleeing; scale is static and should not consume network traffic.
        [Test]
        public void FishTransformReplicatesTheWholeSwimPoseFromServer()
        {
            var fish = SingleFish(scene);
            Assert.IsTrue(fish.TryGetComponent<NetworkTransform>(out var sync), "NetworkTransform is missing");
            Assert.AreEqual(NetworkTransform.AuthorityModes.Server, sync.AuthorityMode);
            Assert.IsTrue(sync.Interpolate, "clients need interpolation to see smooth swimming");
            Assert.IsTrue(sync.SyncPositionX && sync.SyncPositionY && sync.SyncPositionZ,
                "fish movement must replicate on all position axes");
            Assert.IsTrue(sync.SyncRotAngleX && sync.SyncRotAngleY && sync.SyncRotAngleZ,
                "fish pitch/yaw/roll must replicate to guests");
            Assert.IsFalse(sync.SyncScaleX || sync.SyncScaleY || sync.SyncScaleZ,
                "fish scale is static and should not be replicated");
        }

        // NetworkPlayer raycasts both the harpoon and the pickup with
        // QueryTriggerInteraction.Ignore, so a trigger-only fish could never be hit or taken.
        [Test]
        public void FishIsHittableBySolidCollider()
        {
            var fish = SingleFish(scene);
            var colliders = fish.GetComponentsInChildren<Collider>(true);
            Assert.Greater(colliders.Length, 0, "the fish has no collider at all");
            var hittable = false;
            foreach (var collider in colliders)
                if (!collider.isTrigger) hittable = true;
            Assert.IsTrue(hittable, "every fish collider is a trigger, so the harpoon ray passes through");
        }

        [Test]
        public void FishCarriesItsCatchObject()
        {
            var fish = SingleFish(scene);
            Assert.IsTrue(fish.TryGetComponent<CatchObject>(out _),
                "the dead fish becomes the catch in place, so CatchObject shares the NetworkObject");
        }

        // FishMotion holds position instead of leaving the water, so a fish whose wander box
        // pokes outside SwimVolume would spend the dive pinned against a wall.
        [Test]
        public void FishWandersInsideTheWater()
        {
            var fish = SingleFish(scene);
            var water = FindAll<SwimVolume>(scene);
            Assert.AreEqual(1, water.Count, "DiveTestArea must hold exactly one SwimVolume");
            Assert.IsTrue(water[0].TryGetComponent<BoxCollider>(out var volume), "SwimVolume has no BoxCollider");

            var radius = fish.Species.Swim.WanderRadius;
            // FishMotion.VerticalWanderFactor flattens the vertical spread to half.
            var reach = new Vector3(radius, radius * 0.5f, radius);
            var home = fish.transform.position;
            for (var corner = 0; corner < 8; corner++)
            {
                var point = home + new Vector3(
                    (corner & 1) == 0 ? -reach.x : reach.x,
                    (corner & 2) == 0 ? -reach.y : reach.y,
                    (corner & 4) == 0 ? -reach.z : reach.z);
                var local = volume.transform.InverseTransformPoint(point) - volume.center;
                var half = volume.size * 0.5f;
                Assert.IsTrue(
                    Mathf.Abs(local.x) <= half.x && Mathf.Abs(local.y) <= half.y && Mathf.Abs(local.z) <= half.z,
                    $"wander corner {point} falls outside SwimVolume");
            }
        }

        // P2 is a four-player slice. The one target must be immediately testable from every
        // configured dive spawn, and this test reads the real prefab harpoon range instead of
        // duplicating a magic number from NetworkPlayer.
        [Test]
        public void FishStartsInsideHarpoonRangeFromEveryDiveSpawn()
        {
            var fish = SingleFish(scene);
            var spawns = FindAll<PlayerSpawnPoint>(scene);
            Assert.AreEqual(4, spawns.Count, "DiveTestArea must expose four player spawn points");

            var seenSlots = new bool[4];
            var diver = LoadDiverPrefab(out var camera);
            var harpoonRange = SerializedFloat(diver, "harpoonRange");
            Assert.Greater(harpoonRange, 0f, "harpoonRange must be positive");
            var cameraOffset = diver.transform.InverseTransformPoint(camera.transform.position);

            foreach (var spawn in spawns)
            {
                Assert.That(spawn.Slot, Is.InRange(0, 3), "spawn slot must be in the 0..3 co-op range");
                Assert.IsFalse(seenSlots[spawn.Slot], $"duplicate dive spawn slot {spawn.Slot}");
                seenSlots[spawn.Slot] = true;

                var origin = spawn.transform.TransformPoint(cameraOffset);
                var distance = Vector3.Distance(origin, fish.transform.position);
                Assert.LessOrEqual(distance, harpoonRange,
                    $"Fish_SeaBass is {distance:0.00}m from spawn slot {spawn.Slot}, outside the {harpoonRange:0.00}m harpoon range");
            }

            for (var slot = 0; slot < seenSlots.Length; slot++)
                Assert.IsTrue(seenSlots[slot], $"dive spawn slot {slot} is missing");
        }

        // SeaBass health and P2-A harpoon damage are owned by different modules but together
        // define the feel of the only P2 hunt. Lock the agreed three-hit kill so either owner
        // gets a loud test failure instead of silently turning the target into a one-shot or a
        // twenty-second damage sponge.
        [Test]
        public void SeaBassAndHarpoonStayOnTheAgreedThreeHitKill()
        {
            var fish = SingleFish(scene);
            var diver = LoadDiverPrefab(out _);
            var damage = SerializedFloat(diver, "harpoonDamage");
            Assert.Greater(damage, 0f, "harpoonDamage must be positive");

            var hitsToKill = Mathf.CeilToInt(fish.Species.MaxHealth / damage);
            Assert.AreEqual(3, hitsToKill,
                $"SeaBass/harpoon tuning drifted to {hitsToKill} hits; retune both owners intentionally if this changes");
        }

        // The surface is visual only. A collider here would seal the top of the arena and can
        // interfere with the DiveExit volume directly below it.
        [Test]
        public void WaterSurfaceNeverBlocksTheDiveExit()
        {
            GameObject surface = null;
            foreach (var root in scene.GetRootGameObjects())
            {
                if (root.name == "WaterSurface") { surface = root; break; }
                var child = root.transform.Find("WaterSurface");
                if (child != null) { surface = child.gameObject; break; }
            }
            Assert.IsNotNull(surface, "WaterSurface is missing");
            Assert.IsNull(surface.GetComponentInChildren<Collider>(true), "WaterSurface must remain visual-only");
        }

        // docs/plan/PHASES.md P2-B closing condition: "basit sualti sisi/isigi test oncesinde
        // mevcut; geri bildirimsiz bos sahne uzerinden tasarim karari verilmiyor".
        [Test]
        public void UnderwaterAtmosphereIsOn()
        {
            Assert.IsTrue(RenderSettings.fog, "underwater fog is off");
            Assert.AreEqual(FogMode.ExponentialSquared, RenderSettings.fogMode);
            Assert.Greater(RenderSettings.fogDensity, 0f);
            Assert.IsNotNull(RenderSettings.sun, "no sun light is bound for the dive");
        }
    }
}
