using System;
using System.IO;
using DeepDive.Network;
using Unity.Netcode;
using Unity.Netcode.Components;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;
using Object = UnityEngine.Object;

namespace DeepDive.World.Editor
{
    // Authors the P2-B half of DiveTestArea: the one live fish and the underwater atmosphere
    // (docs/plan/PHASES.md P2-B: "Tek baligin yuzme/kacma/vurulma davranisini ... tekil av
    // nesnesini yapar; temel sualti sisi/isigini ekler").
    //
    // Why a script instead of hand-written scene YAML: NetworkObject.GlobalObjectIdHash is
    // generated by Unity from the object's GlobalObjectId (NetworkObject.OnValidate) and it is
    // what a client uses to match its own copy of an in-scene placed NetworkObject. OnValidate
    // is editor-only and does not mark a plain in-scene NetworkObject dirty, so a hand-written
    // value would silently survive into player builds and break host/client matching. Letting
    // Unity author the scene is the only way to be sure the serialized hash is the real one.
    //
    // The fish is in-scene placed on purpose. NetworkSession turns scene management on
    // (NetworkConfig.EnableSceneManagement) and loads the dive through NetworkSceneManager, so
    // NGO synchronises scene objects by that hash and no entry in the shared NetworkPrefabs
    // list is needed. Spawning the fish from a prefab at runtime would need one.
    //
    // Re-running is also the repair path for a bad scene merge: DiveTestArea is shared ground
    // (docs/plan/WORKFLOW.md: "Ayni ana sahne/prefab uzerinde ayni anda calisilmaz"), so this
    // is idempotent - running it twice produces the same scene, never a second fish.
    public static class DiveTestAreaSetup
    {
        private const string ScenePath = "Assets/DeepDive/World/Scenes/DiveTestArea.unity";
        private const string WorldRoot = "Assets/DeepDive/World";
        private const string SpeciesPath = WorldRoot + "/Fish/Species/SeaBass.asset";
        private const string FishMaterialPath = WorldRoot + "/Art/FishMaterial.mat";
        private const string SkyMaterialPath = WorldRoot + "/Art/UnderwaterSky.mat";
        private const string SurfaceMaterialPath = WorldRoot + "/Art/WaterSurfaceMaterial.mat";
        private const string PreviewPath = "Logs/P2-divearea-preview.png";

        public const string FishName = "Fish_SeaBass";
        private const string SurfaceName = "WaterSurface";
        private const string LightName = "Directional Light";

        // Lid over the arena, just above the top of SwimVolume (centre 0,4,0 / size 30,8,30).
        private const float SurfaceHeight = 8.1f;

        // Where the fish lives. Inside SwimVolume (centre 0,4,0 / size 30,8,30) and 8 m in
        // front of the spawn ring (y=1, +-3), well within NetworkPlayer.harpoonRange (22 m).
        // FishMotion treats the placement point as home, so this is also the wander centre.
        private static readonly Vector3 FishHome = new Vector3(0f, 4f, 8f);

        // FishMotion.VerticalWanderFactor: wander offsets are flattened vertically, so the
        // reachable box is shorter than it is wide. Mirrored here to check the placement.
        private const float VerticalWanderFactor = 0.5f;

        [MenuItem("DeepDive/P2/Dive test area: fish and underwater atmosphere")]
        public static void Apply()
        {
            var species = EnsureSpecies();
            var fishMaterial = EnsureFishMaterial();
            var sky = EnsureSkyMaterial();

            var surface = EnsureSurfaceMaterial();

            var scene = EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Single);
            ApplyAtmosphere(sky);
            EnsureWaterSurface(surface);
            var fish = EnsureFish(species, fishMaterial);

            EditorSceneManager.MarkSceneDirty(scene);
            if (!EditorSceneManager.SaveScene(scene))
                throw new InvalidOperationException($"P2_DIVEAREA_SAVE_FAILED scene={ScenePath}");
            AssetDatabase.SaveAssets();

            Debug.Log($"P2_DIVEAREA_READY fish={fish.name} species={species.SpeciesId} " +
                      $"home={FishHome} fogDensity={RenderSettings.fogDensity}");
        }

        // Renders the scene from roughly diver eye height so the atmosphere can be judged from
        // a picture instead of from the numbers. Writes to Logs/ and never saves the scene.
        [MenuItem("DeepDive/P2/Dive test area: write preview image")]
        public static void Preview()
        {
            EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Single);
            var cameraObject = new GameObject("P2PreviewCamera");
            RenderTexture target = null;
            Texture2D image = null;
            try
            {
                var camera = cameraObject.AddComponent<Camera>();
                camera.clearFlags = CameraClearFlags.Skybox;
                camera.nearClipPlane = 0.05f;
                camera.farClipPlane = 1000f;
                camera.fieldOfView = 60f;
                // Diver eye height a few metres off the spawn ring: close enough that the fish
                // is legible and high enough that the water surface is in frame.
                var eye = new Vector3(1.5f, 2.2f, 1.5f);
                cameraObject.transform.position = eye;
                cameraObject.transform.rotation = Quaternion.LookRotation((FishHome - eye).normalized, Vector3.up);

                target = new RenderTexture(1280, 720, 24, RenderTextureFormat.ARGB32);
                camera.targetTexture = target;
                camera.Render();
                camera.targetTexture = null;

                var previous = RenderTexture.active;
                RenderTexture.active = target;
                image = new Texture2D(target.width, target.height, TextureFormat.RGB24, false);
                image.ReadPixels(new Rect(0, 0, target.width, target.height), 0, 0);
                image.Apply();
                RenderTexture.active = previous;

                Directory.CreateDirectory(Path.GetDirectoryName(PreviewPath));
                File.WriteAllBytes(PreviewPath, image.EncodeToPNG());
                Debug.Log($"P2_DIVEAREA_PREVIEW path={PreviewPath}");
            }
            finally
            {
                Object.DestroyImmediate(cameraObject);
                if (image != null) Object.DestroyImmediate(image);
                if (target != null) { target.Release(); Object.DestroyImmediate(target); }
            }
        }

        // docs/plan/CONTRACTS.md ortak veri sozlugu: "SpeciesDefinition | Sabit speciesId ...".
        // speciesId travels over the network and into saves, so it is a real species name and
        // not a placeholder: renaming it later would orphan already recorded captures.
        private static SpeciesDefinition EnsureSpecies()
        {
            EnsureFolder(WorldRoot + "/Fish", "Species");
            var species = AssetDatabase.LoadAssetAtPath<SpeciesDefinition>(SpeciesPath);
            if (species == null)
            {
                species = ScriptableObject.CreateInstance<SpeciesDefinition>();
                AssetDatabase.CreateAsset(species, SpeciesPath);
            }

            var serialized = new SerializedObject(species);
            serialized.FindProperty("speciesId").stringValue = "sea_bass";
            serialized.FindProperty("displayName").stringValue = "Levrek";
            serialized.FindProperty("speciesClass").enumValueIndex = (int)SpeciesClass.Fish;
            // NetworkPlayer.harpoonDamage is 1 with a 0.65 s cooldown and the diver prefab does
            // not override it, so three hits is about two seconds. The 30 default would make
            // one fish a twenty second job. This number is tied to that damage value.
            serialized.FindProperty("maxHealth").floatValue = 3f;
            var weight = serialized.FindProperty("weight");
            // Grams. InventoryManager.CapacityGrams is 20000, so a full bag is around ten fish
            // and the capacity decision still has something to decide.
            weight.FindPropertyRelative("minGrams").intValue = 900;
            weight.FindPropertyRelative("maxGrams").intValue = 2600;
            serialized.FindProperty("swimSpeed").floatValue = 1.2f;
            // Faster than the diver (NetworkPlayer.swimSpeed 3), so the fish cannot be run down
            // and has to be shot from range. A short flee radius keeps that window open.
            serialized.FindProperty("fleeSpeed").floatValue = 3.2f;
            serialized.FindProperty("fleeRadius").floatValue = 5f;
            serialized.FindProperty("wanderRadius").floatValue = 6f;
            serialized.ApplyModifiedPropertiesWithoutUndo();
            EditorUtility.SetDirty(species);

            if (!species.IsValid(out var error))
                throw new InvalidOperationException($"P2_SPECIES_INVALID asset={SpeciesPath} reason={error}");
            return species;
        }

        private static Material EnsureFishMaterial()
        {
            var material = EnsureMaterial(FishMaterialPath, "Universal Render Pipeline/Lit");
            // Warm against the teal fog: the fish has to stay findable once the water is murky.
            material.SetColor("_BaseColor", new Color(0.85f, 0.42f, 0.16f));
            material.SetFloat("_Smoothness", 0.45f);
            material.SetFloat("_Metallic", 0f);
            EditorUtility.SetDirty(material);
            return material;
        }

        // Backstop for the sky. WaterSurface already covers the opening, but any gap at the
        // edges would otherwise show daylight: URP does not apply fog to the skybox, so the
        // default procedural sky stays bright however thick the water gets. Thin atmosphere
        // plus low exposure is what actually darkens this shader; the tint alone does not.
        private static Material EnsureSkyMaterial()
        {
            var material = EnsureMaterial(SkyMaterialPath, "Skybox/Procedural");
            material.SetFloat("_SunDisk", 0f);
            material.SetFloat("_SunSize", 0f);
            material.SetColor("_SkyTint", new Color(0.06f, 0.20f, 0.23f));
            material.SetColor("_GroundColor", new Color(0.02f, 0.07f, 0.09f));
            material.SetFloat("_AtmosphereThickness", 0.35f);
            // Backstop brightness, near the fog colour. The oversized WaterSurface covers the
            // sky from inside the arena, so this only shows if a later change moves the surface
            // or opens the arena up; near-black there would read as a hole, not as water.
            material.SetFloat("_Exposure", 0.6f);
            EditorUtility.SetDirty(material);
            return material;
        }

        private static Material EnsureSurfaceMaterial()
        {
            // Unlit, not Lit. The plane is flipped to face down, so the sun is behind it and
            // ambient reaches it as the dark ground colour: lit, it renders nearly black and
            // looking up reads as a cave roof rather than as the surface. Unlit holds it at a
            // fixed brightness (URP Unlit still takes fog, so distance still fades it), which
            // is the one cue that tells a diver which way is up. Emission on the Lit shader
            // does the same thing but needs the _EMISSION variant for a single flat colour.
            var material = EnsureMaterial(SurfaceMaterialPath, "Universal Render Pipeline/Unlit");
            // Brighter than both the walls and the fog colour, so "up" stays the light side.
            material.SetColor("_BaseColor", new Color(0.13f, 0.34f, 0.40f));
            EditorUtility.SetDirty(material);
            return material;
        }

        // The arena walls stop at y=7 and the dive has no lid, so looking up used to show open
        // sky. A single downward-facing plane closes it and gives the dive an "up" to read
        // against. Renderer only: no collider, so it never blocks the diver or the DiveExit at
        // y=7, and no shadow casting, or the directional light would black out the whole area.
        private static void EnsureWaterSurface(Material material)
        {
            var existing = GameObject.Find(SurfaceName);
            if (existing != null) Object.DestroyImmediate(existing);

            var surface = GameObject.CreatePrimitive(PrimitiveType.Plane);
            surface.name = SurfaceName;
            Object.DestroyImmediate(surface.GetComponent<Collider>());
            surface.transform.position = new Vector3(0f, SurfaceHeight, 0f);
            // Flipped over: an unrotated plane faces up and would be culled from below.
            surface.transform.rotation = Quaternion.Euler(180f, 0f, 0f);
            // 60 x 60 m: twice the arena. A plane the size of the floor ends exactly above the
            // walls, and the diver looks over that edge into a strip of raw skybox that fog
            // never touches - a hard dark line across the top of the dive. Overhanging the
            // walls costs nothing (no collider, no shadow) and removes the strip outright.
            surface.transform.localScale = new Vector3(6f, 1f, 6f);
            var renderer = surface.GetComponent<Renderer>();
            renderer.sharedMaterial = material;
            renderer.shadowCastingMode = ShadowCastingMode.Off;
            renderer.receiveShadows = false;
        }

        private static Material EnsureMaterial(string path, string shaderName)
        {
            EnsureFolder(WorldRoot, "Art");
            var shader = Shader.Find(shaderName);
            if (shader == null)
                throw new InvalidOperationException($"P2_SHADER_MISSING shader={shaderName}");
            var material = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (material == null)
            {
                material = new Material(shader);
                AssetDatabase.CreateAsset(material, path);
            }
            else if (material.shader != shader)
            {
                material.shader = shader;
            }
            return material;
        }

        // Scene lighting only: RenderSettings are stored per scene, so PrepArea and the P1
        // fixtures are untouched. Nothing here needs post processing or a URP asset change
        // (docs/plan/WORKFLOW.md: "katman ve render ayarlari birlikte koordine edilir").
        private static void ApplyAtmosphere(Material sky)
        {
            RenderSettings.fog = true;
            RenderSettings.fogMode = FogMode.ExponentialSquared;
            // Darker than the greybox walls on purpose: the walls are already teal, so a fog
            // the same brightness flattened the room instead of giving it depth.
            RenderSettings.fogColor = new Color(0.035f, 0.145f, 0.175f);
            // Exp2 at 0.055: about 62% fogged at the far wall (18 m from the spawn ring) and
            // still clear enough at 10 m to aim at a fish.
            RenderSettings.fogDensity = 0.055f;

            RenderSettings.ambientMode = AmbientMode.Trilight;
            RenderSettings.ambientSkyColor = new Color(0.12f, 0.32f, 0.38f);
            RenderSettings.ambientEquatorColor = new Color(0.08f, 0.22f, 0.27f);
            RenderSettings.ambientGroundColor = new Color(0.03f, 0.07f, 0.09f);
            RenderSettings.ambientIntensity = 1f;
            RenderSettings.skybox = sky;
            RenderSettings.reflectionIntensity = 0.35f;

            var lightObject = GameObject.Find(LightName);
            if (lightObject == null || !lightObject.TryGetComponent<Light>(out var light))
                throw new InvalidOperationException($"P2_DIVEAREA_NO_LIGHT scene={ScenePath} name={LightName}");
            // Cool and steep, as if it came down through the surface rather than across a field.
            light.color = new Color(0.62f, 0.84f, 0.92f);
            light.intensity = 0.85f;
            light.shadows = LightShadows.Soft;
            light.shadowStrength = 0.55f;
            lightObject.transform.rotation = Quaternion.Euler(70f, -25f, 0f);
            RenderSettings.sun = light;
            DynamicGI.UpdateEnvironment();
        }

        private static GameObject EnsureFish(SpeciesDefinition species, Material material)
        {
            var water = Object.FindFirstObjectByType<SwimVolume>();
            if (water == null || !water.TryGetComponent<BoxCollider>(out var volume))
                throw new InvalidOperationException($"P2_DIVEAREA_NO_WATER scene={ScenePath}");
            RequireWanderRoom(volume, species.Swim.WanderRadius);

            var fish = GameObject.Find(FishName) ?? new GameObject(FishName);
            fish.transform.SetPositionAndRotation(FishHome, Quaternion.identity);
            fish.transform.localScale = Vector3.one;

            Ensure<NetworkObject>(fish);

            var sync = Ensure<NetworkTransform>(fish);
            // The host runs the AI and moves the transform; clients only receive the result
            // (FishActor.FixedUpdate is server only), so the server is the authority here.
            sync.AuthorityMode = NetworkTransform.AuthorityModes.Server;
            sync.Interpolate = true;
            sync.SyncPositionX = sync.SyncPositionY = sync.SyncPositionZ = true;
            // FishActor aims with LookRotation, which pitches when the fish rises or dives, so
            // X has to travel too. The diver prefab can leave it off; a fish cannot.
            sync.SyncRotAngleX = sync.SyncRotAngleY = sync.SyncRotAngleZ = true;
            sync.SyncScaleX = sync.SyncScaleY = sync.SyncScaleZ = false;

            var hull = Ensure<CapsuleCollider>(fish);
            hull.direction = 2; // Z: the fish is long along the axis it swims down.
            hull.radius = 0.16f;
            hull.height = 1.1f;
            hull.center = Vector3.zero;
            // NetworkPlayer raycasts harpoon and pickup with QueryTriggerInteraction.Ignore, so
            // a trigger collider would make the fish unhittable and uncollectable.
            hull.isTrigger = false;

            Ensure<CatchObject>(fish);
            var actor = Ensure<FishActor>(fish);
            var serialized = new SerializedObject(actor);
            serialized.FindProperty("species").objectReferenceValue = species;
            serialized.ApplyModifiedPropertiesWithoutUndo();

            BuildVisual(fish, material);
            return fish;
        }

        // FishMotion holds position rather than leaving the water, so a home whose wander box
        // pokes outside SwimVolume would leave the fish pinned against a wall for the dive.
        // Checked here instead of trusted, because the two constants live in different files.
        private static void RequireWanderRoom(BoxCollider volume, float wanderRadius)
        {
            var reach = new Vector3(wanderRadius, wanderRadius * VerticalWanderFactor, wanderRadius);
            for (var corner = 0; corner < 8; corner++)
            {
                var offset = new Vector3(
                    (corner & 1) == 0 ? -reach.x : reach.x,
                    (corner & 2) == 0 ? -reach.y : reach.y,
                    (corner & 4) == 0 ? -reach.z : reach.z);
                if (Contains(volume, FishHome + offset)) continue;
                throw new InvalidOperationException(
                    $"P2_DIVEAREA_FISH_OUTSIDE home={FishHome} wanderRadius={wanderRadius} corner={FishHome + offset}");
            }
        }

        // The same test SwimVolume.Contains runs at play time, done here without a live
        // component: a plain MonoBehaviour gets no OnEnable in edit mode, so its static
        // registry is empty while the scene is only open in the editor.
        private static bool Contains(BoxCollider volume, Vector3 worldPoint)
        {
            var local = volume.transform.InverseTransformPoint(worldPoint) - volume.center;
            var half = volume.size * 0.5f;
            return Mathf.Abs(local.x) <= half.x && Mathf.Abs(local.y) <= half.y && Mathf.Abs(local.z) <= half.z;
        }

        // Greybox stand-in, not art: a body that reads as a fish and a tail that makes the
        // heading visible, so "the fish is fleeing" is something you can see. Rebuilt every run
        // so a re-run cannot leave half of an older shape behind.
        private static void BuildVisual(GameObject fish, Material material)
        {
            for (var child = fish.transform.childCount - 1; child >= 0; child--)
                Object.DestroyImmediate(fish.transform.GetChild(child).gameObject);

            var body = GameObject.CreatePrimitive(PrimitiveType.Capsule);
            body.name = "Body";
            Object.DestroyImmediate(body.GetComponent<Collider>()); // the root capsule is the target
            body.transform.SetParent(fish.transform, false);
            body.transform.localRotation = Quaternion.Euler(90f, 0f, 0f); // lie along +Z
            body.transform.localScale = new Vector3(0.3f, 0.5f, 0.3f);    // ~1.0 m long, 0.3 m thick
            body.GetComponent<Renderer>().sharedMaterial = material;

            var tail = GameObject.CreatePrimitive(PrimitiveType.Cube);
            tail.name = "Tail";
            Object.DestroyImmediate(tail.GetComponent<Collider>());
            tail.transform.SetParent(fish.transform, false);
            tail.transform.localPosition = new Vector3(0f, 0f, -0.62f);
            tail.transform.localScale = new Vector3(0.04f, 0.34f, 0.3f);
            tail.GetComponent<Renderer>().sharedMaterial = material;
        }

        private static T Ensure<T>(GameObject target) where T : Component
        {
            var component = target.GetComponent<T>();
            return component != null ? component : target.AddComponent<T>();
        }

        private static void EnsureFolder(string parent, string child)
        {
            if (!AssetDatabase.IsValidFolder(parent + "/" + child))
                AssetDatabase.CreateFolder(parent, child);
        }
    }
}
